# Generated by Django 3.1.3 on 2022-01-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='아이디어명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='대표사진')),
                ('content', models.TextField(verbose_name='아이디어설명')),
                ('interest', models.IntegerField(verbose_name='아이디어관심도')),
            ],
        ),
    ]
