# Generated by Django 2.0.13 on 2022-01-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('director', models.CharField(max_length=20, verbose_name='감독')),
                ('actor', models.CharField(max_length=50, verbose_name='주연')),
                ('genre', models.CharField(max_length=20, verbose_name='장르')),
                ('rating', models.FloatField(verbose_name='별점')),
                ('runningTime', models.DurationField(verbose_name='러닝타임')),
                ('content', models.TextField(verbose_name='리뷰내용')),
            ],
        ),
    ]
